# example netlify.toml
[build]
  command = "ng build && ng run uni-plugin-cli-demo:serverless:production"
  functions = "netlify/functions"
  publish = "dist/uni-plugin-cli-demo/browser"

  [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

[[plugins]]
  package = "@netlify/plugin-angular-universal"
  
